### ISSUE TITLE
Do not use the Paymill Bridge

### ISSUE THREAD

**Issue by Nyholm** [memeoirs/paymill-bundle#27]
This bundle is using the [Paymill Bridge](https://developers.paymill.com/en/reference/paymill-bridge/). What is the reason for that? 

Why don't we use the API to issue payments?

**Comment by regularjack** [comment]
The paymill bridge is used to create a token. That token is than used to make requests to the API, server-side. This behavior is described both in the [README](https://github.com/memeoirs/paymill-bundle#accepting-the-payment) and on [Paymill's documentation](https://developers.paymill.com/en/introduction/payment-form/).

I don't think there's another way to use Paymil, considering you probably don't want to send the credit card information to your server.

**Comment by Nyholm** [comment]
Okey, Sorry I have not read the documentation too carefully. 
The reason I ask is because the ajax request to Paymill might be blocked by an adblocker. But I think that is something I should talk with Paymill about. 

One thing we could consider is to display some error message when that ajax request times out.
